/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#b2ac87',
        'on-surface': '#eddeef',
        'on-error-container': '#ffdad6',
        'surface-variant': '#3b323f',
        'background': '#18101c',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-tertiary-fixed': '#1f1c04',
        'primary-fixed': '#ffd9e3',
        'primary-container': '#de739c',
        'error': '#ffb4ab',
        'primary': '#ffb0ca',
        'surface-container': '#251d29',
        'inverse-on-surface': '#362d3a',
        'surface-tint': '#ffb0ca',
        'primary-fixed-dim': '#ffb0ca',
        'surface': '#18101c',
        'on-primary-container': '#5d0833',
        'surface-dim': '#18101c',
        'on-primary-fixed': '#3e001f',
        'on-secondary-container': '#daa9d7',
        'on-tertiary-container': '#444023',
        'on-tertiary': '#353115',
        'tertiary-fixed-dim': '#cec7a0',
        'on-secondary': '#472349',
        'secondary-fixed': '#ffd6fb',
        'on-primary-fixed-variant': '#7d254c',
        'inverse-surface': '#eddeef',
        'on-primary': '#600b36',
        'surface-container-high': '#302734',
        'on-secondary-fixed-variant': '#5f3960',
        'inverse-primary': '#9b3d64',
        'surface-container-low': '#211925',
        'on-surface-variant': '#d9c0c6',
        'secondary-fixed-dim': '#e9b7e6',
        'tertiary': '#cec7a0',
        'tertiary-fixed': '#ebe3bb',
        'on-secondary-fixed': '#2f0d32',
        'outline-variant': '#544247',
        'outline': '#a18b91',
        'on-background': '#eddeef',
        'on-tertiary-fixed-variant': '#4c472a',
        'surface-container-highest': '#3b323f',
        'secondary': '#e9b7e6',
        'surface-container-lowest': '#130b17',
        'surface-bright': '#3f3643',
        'secondary-container': '#623b63',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'gutter-desktop': '1.5rem',
        'margin-mobile': '1rem',
        'margin-desktop': '3rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-2xl': '3rem',
        'space-xs': '0.25rem',
        'gutter-mobile': '1rem',
        'space-xl': '2rem',
        'space-lg': '1.5rem',
        'space-3xl': '4.5rem',
        'card-aspect': '2.5 / 3.5',
        'space-2xs': '0.125rem',
      },
      fontFamily: {
        body: ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        display: ['Space Grotesk', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'display-xl': ['Space Grotesk', 'sans-serif'],
        'display-xl-mobile': ['Space Grotesk', 'sans-serif'],
        label: ['JetBrains Mono', 'monospace'],
        'label-lg': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'stat-metric': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['9px', { lineHeight: '12px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '0em', fontWeight: '600' }],
        'display-xl-mobile': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'stat-metric': ['32px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
