/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#b2ac87',
        'outline': '#a18b91',
        'primary-fixed': '#ffd9e3',
        'on-tertiary-container': '#444023',
        'surface-tint': '#ffb0ca',
        'surface-container-highest': '#393240',
        'on-secondary-fixed': '#2f0d32',
        'on-surface': '#ebdef0',
        'on-primary-container': '#5d0833',
        'surface-bright': '#3e3644',
        'on-error': '#690005',
        'inverse-primary': '#9b3d64',
        'secondary-container': '#623b63',
        'outline-variant': '#544247',
        'primary': '#ffb0ca',
        'on-surface-variant': '#d9c0c6',
        'on-secondary-fixed-variant': '#5f3960',
        'secondary-fixed': '#ffd6fb',
        'surface-container-low': '#1f1926',
        'background': '#17111d',
        'surface-container-lowest': '#120c18',
        'surface-dim': '#17111d',
        'primary-fixed-dim': '#ffb0ca',
        'error-container': '#93000a',
        'surface': '#17111d',
        'inverse-on-surface': '#352e3b',
        'secondary': '#e9b7e6',
        'on-tertiary-fixed-variant': '#4c472a',
        'surface-variant': '#393240',
        'primary-container': '#de739c',
        'on-tertiary': '#353115',
        'surface-container-high': '#2e2734',
        'tertiary-fixed': '#ebe3bb',
        'on-secondary-container': '#daa9d7',
        'on-background': '#ebdef0',
        'on-secondary': '#472349',
        'error': '#ffb4ab',
        'secondary-fixed-dim': '#e9b7e6',
        'surface-container': '#241d2a',
        'on-primary-fixed-variant': '#7d254c',
        'tertiary-fixed-dim': '#cec7a0',
        'on-primary': '#600b36',
        'inverse-surface': '#ebdef0',
        'on-tertiary-fixed': '#1f1c04',
        'tertiary': '#cec7a0',
        'on-primary-fixed': '#3e001f',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Hanken Grotesk', 'sans-serif'],
        code: ['JetBrains Mono', 'monospace'],
        'label-code-lg': ['JetBrains Mono', 'monospace'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'stat-counter': ['Space Grotesk', 'sans-serif'],
      },
      spacing: {
        'space-md': '1rem',
        'card-padding-md': '1.5rem',
        'space-xs': '0.5rem',
        'grid-gutter': '1.5rem',
        'card-padding-lg': '2rem',
        'space-xxs': '0.25rem',
        'space-xl': '2rem',
        'grid-margin': '2rem',
        'space-2xl': '3rem',
        'space-sm': '0.75rem',
        'card-padding-sm': '1rem',
        'space-lg': '1.5rem',
      },
    },
  },
  plugins: [],
};
